import { useTranslation } from 'react-i18next';
import type { TradeData, TradeDetailResponse } from '../services/api';
import { buildTxUrl, truncateHash } from '../utils/stellarExplorer';
import SupportLink from '../components/SupportLink';
import TradeEscrowSummary from '../components/TradeEscrowSummary';

/**
 * WP-D: el recibo, con datos del servidor. Lo que no llega es `null` y la
 * pantalla lo oculta; nunca se rellena con estado local ni con porcentajes.
 */
export interface SuccessReceipt
  extends Pick<
    TradeData,
    'id' | 'status' | 'amount_mxn' | 'seller_id' | 'buyer_id' | 'asset_code' | 'amount_stroops' | 'platform_fee_stroops' | 'total_locked_stroops'
  > {
    lock_tx_hash: string | null;
    release_tx_hash: string | null;
    created_at: string | null;
    completed_at: string | null;
    platform_fee_mxn: number | null;
    provider_fee_mxn: number | null;
    /** Lo que recibe el cliente, ya descontadas las dos comisiones. */
    payout_mxn: number | null;
}

type ServerTrade = TradeData & Partial<Omit<TradeDetailResponse['trade'], keyof TradeData>>;

const numOrNull = (v: unknown): number | null => {
    const n = typeof v === 'string' ? Number(v) : v;
    return typeof n === 'number' && Number.isFinite(n) ? n : null;
};

export function receiptFromServer(
    trade: ServerTrade,
    lockTxHash: string | null,
    releaseTxHash: string | null,
): SuccessReceipt {
    return {
        id: trade.id,
        status: trade.status,
        amount_mxn: trade.amount_mxn,
        seller_id: trade.seller_id,
        buyer_id: trade.buyer_id,
        asset_code: trade.asset_code,
        amount_stroops: trade.amount_stroops,
        platform_fee_stroops: trade.platform_fee_stroops,
        total_locked_stroops: trade.total_locked_stroops,
        lock_tx_hash: trade.lock_tx_hash ?? lockTxHash,
        release_tx_hash: trade.release_tx_hash ?? releaseTxHash,
        created_at: trade.created_at ?? null,
        completed_at: trade.completed_at ?? null,
        platform_fee_mxn: numOrNull(trade.platform_fee_mxn),
        provider_fee_mxn: numOrNull(trade.provider_fee_mxn),
        payout_mxn: numOrNull(trade.payout_mxn),
    };
}

interface SuccessScreenProps {
    type: 'cashout' | 'deposit';
    trade: SuccessReceipt;
    /** Quien mira, para la cifra del escrow que le toca. */
    viewerId?: string | null;
    /** El agente (proveedor). null si no se pudo obtener: no se inventa. */
    agentName: string | null;
    onHome: () => void;
}

/** Returns true when the hash was generated by the mock-Stellar backend. */
function isMockHash(hash: string | null | undefined): boolean {
    return !!hash && hash.startsWith('mock');
}

const SuccessScreen = ({ type, trade, viewerId, agentName, onHome }: SuccessScreenProps) => {
    const { t } = useTranslation();
    const amount = trade.amount_mxn.toFixed(2);
    // Las dos comisiones y el neto salen de la operacion. Antes el neto era
    // `monto - comision de plataforma`, que ignoraba la del agente.
    const commission =
        trade.platform_fee_mxn !== null && trade.provider_fee_mxn !== null
            ? (trade.platform_fee_mxn + trade.provider_fee_mxn).toFixed(2)
            : null;
    const received = trade.payout_mxn !== null ? trade.payout_mxn.toFixed(2) : null;
    const agentLabel = agentName ?? '—';
    const lockTxHash = trade.lock_tx_hash;
    const releaseTxHash = trade.release_tx_hash;

    const isSimulated = isMockHash(lockTxHash) || isMockHash(releaseTxHash);

    const formatTimestamp = (isoString: string | null) => {
        if (!isoString) return '—';
        const date = new Date(isoString);
        const day = date.getDate();
        const month = date.toLocaleString('es-MX', { month: 'short' });
        const hours = date.getHours();
        const minutes = date.getMinutes().toString().padStart(2, '0');
        const ampm = hours >= 12 ? 'pm' : 'am';
        const displayHours = hours % 12 || 12;
        return `${day} ${month} · ${displayHours}:${minutes} ${ampm}`;
    };

    const handleShare = async () => {
        const receiptType = type === 'cashout' ? t('success.receiptWithdrawal') : t('success.receiptDeposit');
        const receiptText = `${t('success.receiptTextTitle', { type: receiptType })}${isSimulated ? ` (${t('success.testnetSimulated')})` : ''}
${t('success.receiptAmount')}: $${amount} MXN
${received !== null ? `${t('success.receiptReceived')}: $${received} MXN` : ''}
${commission !== null ? `${t('success.receiptCommission')}: $${commission} MXN` : ''}
${t('success.receiptAgent')}: ${agentLabel}
${t('success.receiptTradeId')}: ${trade.id}
${lockTxHash ? `${t('success.receiptLock')}: ${truncateHash(lockTxHash, 16)}` : ''}
${releaseTxHash ? `${t('success.receiptRelease')}: ${truncateHash(releaseTxHash, 16)}` : ''}`;

        if (navigator.share) {
            try {
                await navigator.share({
                    title: t('success.receiptTextTitle', { type: receiptType }),
                    text: receiptText,
                });
                return;
            } catch (err) {
                if ((err as Error).name === 'AbortError') return;
            }
        }

        await navigator.clipboard.writeText(receiptText);
        alert(t('success.receiptCopied'));
    };

    return (
        <main className="min-h-screen flex flex-col items-center justify-between px-6 py-12 max-w-md mx-auto bg-surface-container-lowest font-body text-on-surface antialiased">
            {/* Success Header Section */}
            <section className="w-full flex flex-col items-center text-center mt-8">
                {/* Testnet / Simulation badge */}
                {isSimulated && (
                    <div className="mb-4 inline-flex items-center gap-1.5 bg-amber-50 border border-amber-200 text-amber-700 text-xs font-bold uppercase tracking-wider px-3 py-1.5 rounded-full">
                        <span className="material-symbols-outlined text-[14px]">science</span>
                        {t('success.testnetSimulated')}
                    </div>
                )}

                <div className="bg-[#E1F5EE] w-[72px] h-[72px] rounded-full flex items-center justify-center mb-8 ">
                    <span className="material-symbols-outlined text-verde-claro text-[40px]" style={{ fontVariationSettings: '"wght" 600' }}>
                        {type === 'cashout' ? 'check' : 'check_circle'}
                    </span>
                </div>
                <h1 className="font-headline font-extrabold text-4xl tracking-tight mb-2">
                    {type === 'cashout' ? t('success.cashoutDone') : t('success.depositDone')}
                </h1>
                <p className="text-secondary font-medium text-lg opacity-70">
                    {type === 'cashout' ? t('success.cashoutSubtitle') : t('success.depositSubtitle')}
                </p>
            </section>

            {/* Summary Card */}
            <section className="w-full bg-[#f6f7f8] rounded-sm p-6 my-8 space-y-5 ">
                <div className="space-y-4">
                    <div className="flex justify-between items-center">
                        <span className="text-on-surface-variant font-medium text-sm">
                            {type === 'cashout' ? t('success.mxnSent') : t('success.cashDelivered')}
                        </span>
                        <span className="num font-bold text-on-surface">${amount}</span>
                    </div>
                    {received !== null ? (
                        <div className="flex justify-between items-center">
                            <span className="text-on-surface-variant font-medium text-sm">
                                {type === 'cashout' ? t('success.cashReceived') : t('success.mxneReceived')}
                            </span>
                            <span className="font-bold text-primary text-lg">${received}</span>
                        </div>
                    ) : null}
                    {commission !== null ? (
                        <div className="flex justify-between items-center">
                            <span className="text-on-surface-variant font-medium text-sm">{t('success.commission')}</span>
                            <span className="font-medium text-on-surface">-${commission}</span>
                        </div>
                    ) : null}
                    <TradeEscrowSummary trade={trade} viewerId={viewerId} />
                </div>

                <div className="h-[1px] w-full bg-outline-variant/10"></div>

                <div className="space-y-4">
                    <div className="flex justify-between items-start">
                        <span className="text-on-surface-variant font-medium text-sm">{t('success.agent')}</span>
                        <div className="text-right">
                            <p className="font-semibold text-on-surface text-sm">{agentLabel}</p>
                            <div className="flex items-center justify-end gap-1 mt-0.5 text-primary">
                                <span className="material-symbols-outlined text-[14px]" style={{ fontVariationSettings: '"FILL" 1' }}>verified</span>
                                <span className="text-[10px] font-bold uppercase tracking-wider">{t('success.verified')}</span>
                            </div>
                        </div>
                    </div>
                    <div className="flex justify-between items-center">
                        <span className="text-on-surface-variant font-medium text-sm">{t('success.dateTime')}</span>
                        <span className="text-on-surface text-sm font-medium">{formatTimestamp(trade.completed_at ?? trade.created_at)}</span>
                    </div>
                </div>
            </section>

            {/* Receipt — trade evidence */}
            <section className="w-full bg-papel border-2 border-tinta rounded-sm p-5 mb-6 space-y-3">
                <h3 className="text-[11px] font-bold text-gris uppercase tracking-[0.15em] mb-3">{t('success.receiptTitle')}</h3>

                <div className="flex justify-between items-center">
                    <span className="text-on-surface-variant text-xs">{t('success.tradeId')}</span>
                    <span className="font-mono text-xs text-on-surface">{trade.id.slice(0, 8)}…</span>
                </div>

                <div className="flex justify-between items-center">
                    <span className="text-on-surface-variant text-xs">{t('success.status')}</span>
                    <span className="text-xs font-semibold text-on-surface capitalize">{trade.status}</span>
                </div>

                {lockTxHash && (
                    <div className="flex justify-between items-center">
                        <span className="text-on-surface-variant text-xs">
                            {t('success.lockTx')} {isMockHash(lockTxHash) && <span className="text-amber-600">{t('success.simulated')}</span>}
                        </span>
                        {isMockHash(lockTxHash) ? (
                            <span className="font-mono text-xs text-on-surface-variant opacity-60">{truncateHash(lockTxHash, 8)}</span>
                        ) : (
                            <a href={buildTxUrl(lockTxHash)} target="_blank" rel="noopener noreferrer"
                                className="font-mono text-xs text-primary hover:underline">{truncateHash(lockTxHash, 8)}</a>
                        )}
                    </div>
                )}

                {releaseTxHash && (
                    <div className="flex justify-between items-center">
                        <span className="text-on-surface-variant text-xs">
                            {t('success.releaseTx')} {isMockHash(releaseTxHash) && <span className="text-amber-600">{t('success.simulated')}</span>}
                        </span>
                        {isMockHash(releaseTxHash) ? (
                            <span className="font-mono text-xs text-on-surface-variant opacity-60">{truncateHash(releaseTxHash, 8)}</span>
                        ) : (
                            <a href={buildTxUrl(releaseTxHash)} target="_blank" rel="noopener noreferrer"
                                className="font-mono text-xs text-primary hover:underline">{truncateHash(releaseTxHash, 8)}</a>
                        )}
                    </div>
                )}

                <div className="flex justify-between items-center">
                    <span className="text-on-surface-variant text-xs">{t('success.created')}</span>
                    <span className="text-xs text-on-surface">{formatTimestamp(trade.created_at)}</span>
                </div>

                {trade.completed_at && (
                    <div className="flex justify-between items-center">
                        <span className="text-on-surface-variant text-xs">{t('success.completed')}</span>
                        <span className="text-xs text-on-surface">{formatTimestamp(trade.completed_at)}</span>
                    </div>
                )}

                <div className="pt-2 text-center">
                    <SupportLink tradeId={trade.id} state="SUCCESS" />
                </div>
            </section>

            {/* Hash & Rating */}
            <div className="w-full space-y-8 text-center">
                {/* Transaction hashes */}
                <section className="space-y-4">
                    {releaseTxHash && !isMockHash(releaseTxHash) && (
                        <div>
                            <a
                                href={buildTxUrl(releaseTxHash)}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-primary font-bold text-sm hover:opacity-80 transition-opacity flex items-center justify-center gap-2 mx-auto"
                            >
                                {t('success.viewRelease')}
                                <span className="material-symbols-outlined text-[18px]">open_in_new</span>
                            </a>
                            <p className="font-mono text-[11px] text-on-surface-variant opacity-60 tracking-tight mt-1">
                                {truncateHash(releaseTxHash, 8)}
                            </p>
                        </div>
                    )}
                    {lockTxHash && !releaseTxHash && !isMockHash(lockTxHash) && (
                        <div>
                            <a
                                href={buildTxUrl(lockTxHash)}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-primary font-bold text-sm hover:opacity-80 transition-opacity flex items-center justify-center gap-2 mx-auto"
                            >
                                {t('success.viewLock')}
                                <span className="material-symbols-outlined text-[18px]">open_in_new</span>
                            </a>
                            <p className="font-mono text-[11px] text-on-surface-variant opacity-60 tracking-tight mt-1">
                                {truncateHash(lockTxHash, 8)}
                            </p>
                        </div>
                    )}
                    {(!lockTxHash && !releaseTxHash) && (
                        <span className="text-primary font-bold text-sm opacity-40 flex items-center justify-center gap-2">
                            {t('success.viewOnChain')}
                            <span className="material-symbols-outlined text-[18px]">open_in_new</span>
                        </span>
                    )}
                </section>

                {/* Share button */}
                <section>
                    <button
                        onClick={handleShare}
                        className="text-primary font-bold text-sm hover:opacity-80 transition-opacity flex items-center justify-center gap-2 mx-auto bg-primary/10 px-4 py-2 rounded-sm"
                    >
                        {t('success.shareReceipt')}
                        <span className="material-symbols-outlined text-[18px]">share</span>
                    </button>
                </section>

                {/* Star rating */}
                {agentName ? <section>
                    <p className="text-on-surface-variant font-medium text-sm mb-4">{t('success.howWasService', { agentName })}</p>
                    <div className="flex justify-center gap-2">
                        {[1, 2, 3, 4, 5].map((star) => (
                            <span
                                key={star}
                                className="material-symbols-outlined text-gris text-[32px] cursor-pointer hover:text-primary transition-colors"
                            >
                                star
                            </span>
                        ))}
                    </div>
                </section> : null}
            </div>

            {/* Primary Action */}
            <div className="w-full pt-8">
                <button
                    onClick={onHome}
                    className="w-full h-[54px] bg-naranja text-papel border-2 border-tinta shadow-solida font-bold rounded-sm active:translate-x-[2px] active:translate-y-[2px] transition-all flex items-center justify-center gap-2"
                >
                    {t('success.backToHome')}
                    <span className="material-symbols-outlined">arrow_forward</span>
                </button>
            </div>
        </main>
    );
};

export default SuccessScreen;
